[2024-07-10T11:39:22.609+0000] {scheduler_job_runner.py:769} ERROR - Executor reports task instance <TaskInstance: spaceX_project.load_charachteristics scheduled__2024-07-09T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
