[2024-07-09T09:15:55.173+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T09:15:55.251+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.transform manual__2024-07-09T09:15:47.392278+00:00 [queued]>
[2024-07-09T09:15:55.271+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.transform manual__2024-07-09T09:15:47.392278+00:00 [queued]>
[2024-07-09T09:15:55.272+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-09T09:15:55.300+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-07-09 09:15:47.392278+00:00
[2024-07-09T09:15:55.320+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=780) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-09T09:15:55.325+0000] {standard_task_runner.py:63} INFO - Started process 785 to run task
[2024-07-09T09:15:55.323+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'transform', 'manual__2024-07-09T09:15:47.392278+00:00', '--job-id', '516', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpra0xv065']
[2024-07-09T09:15:55.328+0000] {standard_task_runner.py:91} INFO - Job 516: Subtask transform
[2024-07-09T09:16:04.393+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.transform manual__2024-07-09T09:15:47.392278+00:00 [running]> on host f565c82ff71d
[2024-07-09T09:16:05.979+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T09:15:47.392278+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T09:15:47.392278+00:00'
[2024-07-09T09:16:05.982+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T09:16:06.123+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T09:16:06.130+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 18, in transform
    df = pd.json_normalize(data.json())
                           ^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'json'
[2024-07-09T09:16:06.232+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spaceX_project, task_id=transform, run_id=manual__2024-07-09T09:15:47.392278+00:00, execution_date=20240709T091547, start_date=20240709T091555, end_date=20240709T091606
[2024-07-09T09:16:06.515+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 516 for task transform ('NoneType' object has no attribute 'json'; 785)
[2024-07-09T09:16:06.634+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T09:16:06.680+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T09:16:06.686+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
