[2024-07-09T09:20:45.524+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-09T09:20:45.561+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceX_project.transform manual__2024-07-09T09:15:47.392278+00:00 [queued]>
[2024-07-09T09:20:45.574+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceX_project.transform manual__2024-07-09T09:15:47.392278+00:00 [queued]>
[2024-07-09T09:20:45.575+0000] {taskinstance.py:2306} INFO - Starting attempt 7 of 7
[2024-07-09T09:20:45.599+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform> on 2024-07-09 09:15:47.392278+00:00
[2024-07-09T09:20:45.611+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=862) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-09T09:20:45.610+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spaceX_project', 'transform', 'manual__2024-07-09T09:15:47.392278+00:00', '--job-id', '523', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp9649zj7y']
[2024-07-09T09:20:45.615+0000] {standard_task_runner.py:91} INFO - Job 523: Subtask transform
[2024-07-09T09:20:45.615+0000] {standard_task_runner.py:63} INFO - Started process 871 to run task
[2024-07-09T09:20:45.692+0000] {task_command.py:426} INFO - Running <TaskInstance: spaceX_project.transform manual__2024-07-09T09:15:47.392278+00:00 [running]> on host f565c82ff71d
[2024-07-09T09:20:45.820+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rustam' AIRFLOW_CTX_DAG_ID='spaceX_project' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2024-07-09T09:15:47.392278+00:00' AIRFLOW_CTX_TRY_NUMBER='7' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-09T09:15:47.392278+00:00'
[2024-07-09T09:20:45.822+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-09T09:20:45.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-09T09:20:45.860+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag.py", line 18, in transform
    df = pd.json_normalize(data.json())
                           ^^^^^^^^^
AttributeError: 'list' object has no attribute 'json'
[2024-07-09T09:20:45.875+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=spaceX_project, task_id=transform, run_id=manual__2024-07-09T09:15:47.392278+00:00, execution_date=20240709T091547, start_date=20240709T092045, end_date=20240709T092045
[2024-07-09T09:20:45.890+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 523 for task transform ('list' object has no attribute 'json'; 871)
[2024-07-09T09:20:45.911+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-09T09:20:45.934+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-09T09:20:45.936+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
